version: "3"

services:
  carrental:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    env_file: ./local.env
    ports: 
      - 8080:80
    volumes: 
      - .:/var/www/html
      - ./docker/logs:/var/log/nginx
      - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
      - ./docker/config/app.conf:/etc/nginx/conf.d/default.conf
      - /var/www/html/vendor/
      - /var/www/html/storage/
    networks:
      - sail
    depends_on: 
      - mysql

  mysql:
    image: mysql:5.7
    build: ./database
    ports: 
      - 3306:3306
    restart: always
    volumes: 
      - ./database/sql:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
    networks:
      - sail

  myadmin:
    build:
      context: ./docker
      dockerfile: phpmyadmin.Dockerfile
    volumes:
      - /sessions
    networks:
      - sail
    links:
      - mysql
    ports:
      - "8089:80"
    container_name: myadmin

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - sail

networks:
  sail:
    driver: bridge
      